import { useState, useEffect } from 'react';
import { FileText, Download, Filter, Loader2 } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './Reports.css';

const Reports = () => {
  const [pastReports, setPastReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from('uploads')
        .select(`
          *,
          user:user_id (email)
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;

      const formatted = data.map(r => ({
        id: r.id.substring(0, 8).toUpperCase(),
        fullId: r.id,
        date: new Date(r.created_at).toLocaleDateString('en-IN'),
        totalDocs: r.doc_count,
        matches: r.doc_count - r.fraud_count,
        fraud: r.fraud_count,
        user: r.user?.email || 'System',
        outlet: r.outlet
      }));

      setPastReports(formatted);
    } catch (err) {
      console.error('Error fetching reports:', err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="reports-page">
      <div className="page-header-actions">
        <div>
          <h1>Past Reports</h1>
          <p>Access and download previously generated fraud analysis reports.</p>
        </div>
        <button className="btn-primary flex-center gap-2" style={{ backgroundColor: 'var(--bg-card)', color: 'var(--text-primary)', border: '1px solid var(--border-color)' }}>
          <Filter size={18} /> Filter Reports
        </button>
      </div>

      <div className="card table-container">
        <div className="table-wrapper">
          <table className="reports-table">
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Date Generated</th>
                <th>Total Documents</th>
                <th>Matches</th>
                <th>Fraud Alerts</th>
                <th>Generated By</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan="7" style={{ textAlign: 'center', padding: '4rem' }}>
                    <Loader2 className="animate-spin" size={32} color="var(--primary)" style={{ margin: '0 auto' }} />
                  </td>
                </tr>
              ) : pastReports.length === 0 ? (
                <tr>
                  <td colSpan="7" style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-secondary)' }}>
                    No reports available.
                  </td>
                </tr>
              ) : (
                pastReports.map((report) => (
                  <tr key={report.id}>
                    <td>
                      <div className="report-id-cell">
                        <FileText size={16} className="text-secondary" />
                        <span className="font-medium">{report.id}</span>
                      </div>
                    </td>
                    <td>{report.date}</td>
                    <td>{report.totalDocs}</td>
                    <td className="green-text font-medium">{report.matches}</td>
                    <td className={report.fraud > 0 ? 'red-text font-medium' : ''}>{report.fraud}</td>
                    <td>{report.user}</td>
                    <td>
                      <button className="action-btn" title="Download PDF">
                        <Download size={18} />
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Reports;
